/**
 * M4.8 / D119, D60's rule for the comic: `templates/comic/sample/` is the
 * canonical sample comic, the one `papeleria new comic` copies and the
 * package ships; `examples/sample-comic/` is the seeded repository example,
 * kept byte-identical by this test. Its art changes only through
 * `scripts/gen-sample-comic.mjs` (D102), which writes the example: run it,
 * then copy the pages over the sample in the same commit. The sample is
 * self-contained: it names only files it has and has every file it names;
 * the one file it holds besides them is the pages' provenance note, and it
 * carries nothing generated by a build.
 */
import assert from 'node:assert/strict';
import {lstatSync, readdirSync, readFileSync} from 'node:fs';
import {join} from 'node:path';
import {test} from 'node:test';

import {parse} from 'yaml';

import {applicationRoot} from '../helpers/paths.js';
import {readTree} from '../helpers/pieces.js';

const SAMPLE = join(applicationRoot, 'templates', 'comic', 'sample');
const EXAMPLE = join(applicationRoot, 'examples', 'sample-comic');
const PAGES = ['01', '02', '03', '04', '05', '06', '07', '08'].map((page) => `assets/images/pages/${page}.png`);
const PROVENANCE = 'assets/images/pages/README.md';

/** Every entry under a folder that is not a regular file or a folder, such as a link. */
function irregular(directory: string): string[] {
  return readdirSync(directory).flatMap((name) => {
    const path = join(directory, name);
    const stat = lstatSync(path);
    return stat.isDirectory() ? irregular(path) : stat.isFile() ? [] : [path];
  });
}

/** Every string in a parsed manifest that names a file under assets/. */
function assetReferences(value: unknown): string[] {
  if (typeof value === 'string') {
    return value.startsWith('assets/') ? [value] : [];
  }
  if (Array.isArray(value)) {
    return value.flatMap(assetReferences);
  }
  return value !== null && typeof value === 'object' ? Object.values(value).flatMap(assetReferences) : [];
}

test('D60, D119: the comic sample and examples/sample-comic are the same files, byte for byte', () => {
  const sample = readTree(SAMPLE);
  const example = readTree(EXAMPLE);
  assert.deepEqual(Object.keys(sample).sort(), Object.keys(example).sort());
  for (const [path, bytes] of Object.entries(sample)) {
    assert.ok(Buffer.from(bytes).equals(Buffer.from(example[path]!)), `${path} differs; copy one over the other`);
  }
  assert.deepEqual(Object.keys(sample).sort(), [...PAGES, PROVENANCE, 'assets/text/gull-note.md', 'papeleria.yaml']);
});

test('IC09: the sample is self-contained regular files naming only what it holds, with nothing a build writes in it', () => {
  assert.deepEqual(irregular(SAMPLE), []);
  assert.deepEqual(readdirSync(SAMPLE).sort(), ['assets', 'papeleria.yaml'], 'no dist/ or .papeleria/ travels with the sample');
  const manifest = parse(readFileSync(join(SAMPLE, 'papeleria.yaml'), 'utf8')) as {template: string; pages: {panels: {detail?: object}[]}[]};
  assert.equal(manifest.template, 'comic');
  const named = [...new Set(assetReferences(manifest))].sort();
  const held = Object.keys(readTree(SAMPLE)).filter((path) => path.startsWith('assets/') && path !== PROVENANCE).sort();
  assert.deepEqual(named, held, 'every file it names is there, and it holds nothing else but the pages’ provenance note');
  assert.equal(manifest.pages.length, 8);
  const details = manifest.pages.flatMap((page) => page.panels.map((panel) => (panel.detail === undefined ? 'none' : Object.keys(panel.detail)[0])));
  assert.deepEqual([...new Set(details)].sort(), ['none', 'text', 'zoom'], 'the sample shows a zoom, a text detail and panels without one');
});

test('the sample never passes for published work: its pages and credits say they are placeholders (PRD §11, D102)', () => {
  const manifest = readFileSync(join(SAMPLE, 'papeleria.yaml'), 'utf8');
  assert.match(manifest, /^status: draft$/m);
  const parsed = parse(manifest) as {credits: {name: string}[]; pages: {credit: string; rights: string}[]};
  assert.deepEqual(parsed.credits.map((credit) => credit.name), ['Placeholder art, generated']);
  for (const page of parsed.pages) {
    assert.equal(page.credit, 'Placeholder art, generated');
    assert.match(page.rights, /no rights claimed/);
  }
});
